const name = [
  "Liam",
  "Noah",
  "Oliver",
  "Elijah",
  "James",
  "William",
  "Benjamin",
  "Jonathan",
  "Henry",
  "Theodore",
  "Jack",
  "Levi",
  "Alexander",
  "Jackson",
  "Mateo",
  "Lucas",
  "Olivia",
  "Emma",
  "Charlotte",
  "Amelia",
  "Ava",
  "Sofia",
  "Sophia",
  "Isabella",
  "Mia",
  "Evelyn",
  "Harper",
  "Camila",
  "Gianna",
  "Elizabeth",
];
const lastName = [
  "Smith",
  "Gonzales",
  "Damon",
  "West",
  "Madison",
  "Adler",
  "Hope",
  "Lopez",
  "Keller",
  "Jenkins",
  "Ford",
  "Zimmerman",
  "Gray",
  "Adams",
  "Boselli",
  "Lewis",
  "Robinson",
  "Walker",
  "Young",
  "Allen",
  "King",
  "Wright",
  "Scott",
  "Torres",
  "Nguyen",
  "Hill",
  "Flores",
  "Escobar",
  "Green",
  "Nelson",
];
const hobbie = [
  "Animation",
  "Blacksmith",
  "Book restoration",
  "Chatting",
  "Cooking",
  "Cryptography",
  "Diving",
  "Fishkeeping",
  "Gardening",
  "Hacking",
  "Inventing",
  "Judo",
  "Karate",
  "Livestreaming",
  "Meditation",
  "Dancing",
  "Singing",
  'Reading',
  'Scuba diving',
  'Shitposting',
  'Storytelling',
  'Taekwondo',
  'Watching movies',
  'Wikipedia editing',
  'Witchcraft',
  'Writing',
  'Yoga',
  'Airsoft',
  'Automobilism',
  'Basketball'
];

const age = [
  20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
  39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
];
const favoriteColor = [
  "red",
  "blue",
  "yellow",
  "gray",
  "brown",
  "red",
  "pink",
  "orange",
  "Silver",
  "Maroon",
  "Beige",
  "Peach",
  "Lime",
  "Olive",
  "Turquoise",
  "Teal",
  "Navy blue",
  "Indigo",
  "Violet",
  "Green",
  "Cyan",
  "Magenta",
  "Purple",
  "White",
  "Indigo",
  "Black",
  "Ivory",
  "Gold",
  "Coral",
  "Salmon",
];

const country = [
  "England",
  "Brazil",
  "United States",
  "Mexico",
  "Colombia",
  "Spain",
  "Egipt",
  "Uruguay",
  "Chile",
  "Argentina",
  "China",
  "Japan",
  "Germany",
  "Portugal",
  "Sweden",
];
const basicProfilePictures = 
['https://blog.za3k.com/wp-content/uploads/2015/03/default_profile_1_bigger.png',
'https://blog.za3k.com/wp-content/uploads/2015/03/default_profile_2_bigger.png',
'https://blog.za3k.com/wp-content/uploads/2015/03/default_profile_3_bigger.png',
'https://blog.za3k.com/wp-content/uploads/2015/03/default_profile_4_bigger.png',
'https://blog.za3k.com/wp-content/uploads/2015/03/default_profile_5_bigger.png',
'https://blog.za3k.com/wp-content/uploads/2015/03/default_profile_6_bigger.png']


module.exports = Object.freeze({
  name,
  lastName,
  age,
  favoriteColor,
  country,
  hobbie,
  basicProfilePictures
});
